### Create User

POST http://localhost:3000/api/signup
Content-Type: application/json

{
"first_name": "Shashi",
"last_name": "Shekhar",
"email": "Shekhars094@gmail.com",
"user_name":"shekhar/501",
"password": "12345678"
}

### Login User

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "Shekhars094@gmail.com",
    "password":"12345678"
}

### SignOut User

GET http://localhost:3000/api/signout


### Creating News Post

POST http://localhost:3000/api/user/5eabe71a612ab9820325c7b0/news
Content-Type: application/json

{
    "newsTitle":"Rohit Sharma Birthday",
    "newsArticle": "SomeThing Bad is Happening in The World"
}
